# Site settings
title: "Vaple"
description: |
    Sardinia, Italy

    August 2nd, 2019
owner: Vaple
first_published: 2018
email: 
baseurl: "" # the subpath of your site, e.g. /blog
url: " # the base hostname & protocol for your site

social:
  github: https://github.com/principessamia

# Build settings
markdown: kramdown
